# Example .streamlit/secrets.toml file
# Replace this with your actual credentials from your credentials.json file

[gcp_service_account]
type = "service_account"
project_id = "rn-copy-checker-app"
private_key_id = "6bdd1e46035630f4be801727a028519c6f8faf14"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC... (your full private key here)
-----END PRIVATE KEY-----"""
client_email = "your-service-account@rn-copy-checker-app.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40rn-copy-checker-app.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Note: 
# 1. Copy each field EXACTLY from your credentials.json file
# 2. Use triple quotes (""") for the private_key field to handle multiline content
# 3. Make sure there are no extra spaces or characters
# 4. Do NOT include the gcp_creds field if using this method 